### ISSUE TITLE
I require use join of DQL queries, does clever-backgroud-task support it?

### ISSUE THREAD

**Issue by thinksource** [CleverStack/clever-background-tasks#13]
I need to run with like:

$query = $em->createQuery("SELECT u FROM User u JOIN u.address a WHERE a.city = 'Berlin'");

Is there anyway to do it?

**Comment by pilsy** [comment]
Typically when using the Background Task's module you will be using clever-orm and/or clever-odm, take a look at http://cleverstack.io/documentation/backend/models/#finders-find-options-include for information about this.

So you would end up with something like this

```
UserModel.find({
  include: [
    {
      model: AccountModel,
      where: {
        city: 'Berlin'
      },
      required: true // this might or might not be needed
    }
  ]
});
```

Let me know if you need help setting up something specific
